In [ ]:
#export
"""These are pretty standard imports that I always
do. I put it here so that I can do::

    from k1lib.imports import *

and everything will be in place"""
try:
    import torch; from torch import nn, optim
    import torch.nn.functional as F, torch.utils.data as data
except: pass
import matplotlib.pyplot as plt, matplotlib as mpl
import numpy as np, dill as pickle, multiprocessing as mp, concurrent.futures as futures
import math, os, time, sys, random, logging, traceback, re, typing, glob, warnings, asyncio
import dill, json, inspect, xml, base64, io
import functools; from functools import partial, lru_cache
import contextlib; from contextlib import contextmanager
from collections import deque, defaultdict
from typing import List, Tuple, Callable, Union, Iterator, Set, Dict, Any
import k1lib; from k1lib import schedule, graphEqn, mo, knn, fmt, selector,\
viz, Cbs, settings, cli, _k1a, serve, p5, k1ui
from k1lib.cli import *; k1 = k1lib; k1a = _k1a
for e in cli._scatteredClis: globals()[e.__name__] = e
if "py_k1lib_in_applyMp" not in os.environ: k1lib.dontWrap()
plt.rcParams['figure.dpi'] = 100
plt.rcParams["animation.html"] = "jshtml"

In [ ]:
#export
from math import e, pi; inf = float("inf"); nan = float("nan"); # this section is for constants
h = 6.62607015e-34; hbar = h/(2*pi); Na = 6.0221408e23; kb = 1.380649e-23
c = 299_792_458; qe = 1.60217663e-19; me = 9.1093837e-31; mn = 1.67262192e-27
e0 = 8.85418782e-12; Dal = u = 1.6605390666e-27; R = 8.3145; sb = 5.670374e-8

In [ ]:
#export
if settings.startup.or_patch.numpy: cli.init.patchNumpy()
if settings.startup.or_patch.dict: cli.init.patchDict()
try:
    import pandas as pd
    if settings.startup.or_patch.pandas: cli.init.patchPandas()
except ImportError as e: pass

In [ ]:
#notest
# this is for local test, edge case so can't be tested with the masses
assert d | op().keys() | deref() == ['a', 'b']
assert d | op().items() | deref() == [['a', 3], ['b', 4]]

In [ ]:
d = {"a": 3, "b": 4}
a = np.linspace(0, 100, dtype=int)
b = np.linspace(0, 100, dtype=int)
a | b, a | head(3) | deref(), a | apply(op() | 100) | head(3) | deref()

(array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
         26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  51,
         53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
         79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100]),
 array([0, 2, 4]),
 [100, 102, 104])

In [ ]:
a | 3

array([  3,   3,   7,   7,  11,  11,  15,  15,  19,  19,  23,  23,  27,
        27,  31,  31,  35,  35,  39,  39,  43,  43,  47,  47,  51,  51,
        55,  55,  59,  59,  63,  63,  67,  67,  71,  71,  75,  75,  79,
        79,  83,  83,  87,  87,  91,  91,  95,  95,  99, 103])

In [ ]:
#export
def dummy():
    """Does nothing. Only here so that you can read source code of this file
and see what's up."""
    pass

In [1]:
#export
try: # these are optional imports
    import torchvision as vision
    import torchvision.datasets as tvDs
    import torchvision.transforms as tf
except: pass
try: import IPython
except: pass
try: import PIL
except: pass
try: from scipy.optimize import fsolve; import scipy
except: pass
try: import einops
except: pass
try: from tqdm import tqdm
except: pass
try: import sympy
except: pass
try: import rdkit; from rdkit import Chem
except: pass
try: import requests
except: pass
try: import seaborn as sns
except: pass

In [3]:
!../export.py imports

Current dir: /home/kelvin/repos/labs/k1lib, /home/kelvin/repos/labs/k1lib/k1lib/../export.py
rm: cannot remove '__pycache__': No such file or directory
Found existing installation: k1lib 1.2
Uninstalling k1lib-1.2:
  Successfully uninstalled k1lib-1.2
running install
/home/kelvin/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/kelvin/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating k1lib.egg-info
writing k1lib.egg-info/PKG-INFO
writing dependency_links to k1lib.egg-info/dependency_links.txt
writing requirements to k1lib.egg-info/requires.txt
writing top-level names to k1lib.egg-info/top_level.txt
writin